server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true  # IMPORTANTE: Isso faz o data.sql executar após a criação das tabelas
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always  # Garante que os scripts SQL sejam sempre executados